### ISSUE TITLE
Bump keycloak-operator from 1.15.0 to 1.17.0 in the extensions-oidc

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-cluster-add-ons#15]
Bump keycloak-operator from 1.15.0 to 1.17.0 in the extensions-oidc

**Comment by mukovozovb** [comment]
Bump keycloak operator in add-ons repo. Change deprecated parameters realm and target realm in KeycloakClientScope and KeycloakClient to realm ref.

This issues resolved in ticket number #17
