### ISSUE TITLE
As a EDP User, I want to have capability to configure Sonar with sonar-operator as a part of add-ons approach

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-cluster-add-ons#3]
Acceptance Criteria:

- [edp-cluster-add-ons](https://github.com/epam/edp-cluster-add-ons) repository contain templates to deploy sonar-operator;
- sonar-operator configure and prepare Sonar for integration with EDP;

**Comment by Rolika4** [comment]
In [patch](https://github.com/epam/edp-cluster-add-ons/commit/99b928a1416fbb5a56bae2daaa6ca6d2c4a3c30a) we add the capability to configure upstream sonar with edp-sonar-operator. All templates added to [edp-cluster-add-ons](https://github.com/epam/edp-cluster-add-ons) repository.
